[package]
name = "CherrySTUNExample"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
log = "0.4.22"
log4rs = "1.3.0"
simple_logger = "5.0.0"

[dependencies.CherrySTUN]
path = "../CherrySTUN"

